services:
  auth:
    build: ./auth
    container_name: auth
    environment:
      DB_HOST: auth-postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      DB_SSL_MODE: disable
      SERVER_PORT: 8080
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      auth-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
  otp:
    build: ./otp
    container_name: otp
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SENDER: ${SMTP_SENDER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
      otp-redis:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    restart: unless-stopped
  auth-postgres:
    image: postgres:latest
    container_name: auth-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./auth-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    environment:
      TF_VAR_rabbitmq_user: ${RABBITMQ_USER}
      TF_VAR_rabbitmq_password: ${RABBITMQ_PASSWORD}
    volumes:
      - ./terraform:/app
    working_dir: /app
    entrypoint: [ "sh", "-c", "terraform init && terraform apply -auto-approve" ]
    depends_on:
      rabbitmq:
        condition: service_healthy
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # Web UI port
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8025/api/v2/messages"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  otp-redis:
    image: redis:latest
    container_name: otp-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
