services:
  auth-postgres:
    image: postgres:latest
    container_name: auth-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./auth-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  nats:
    image: nats:latest
    # "-js" enables JetStream. "-sd" sets the storage directory.
    command: "-js -m 8222 -sd /data"
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # HTTP Monitoring dashboard
    volumes:
      - ./nats_data:/data
  nats-box:
    image: natsio/nats-box:latest
    depends_on:
      - nats
    command: 
      - /bin/sh
      - -c
      - "sleep infinity"
    environment:
      - NATS_URL=nats://nats:4222
